name: Build 0.6.x Plugin

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:

  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master (0.6.x)
      uses: actions/checkout@v4
      with:
        ref: 0.6.x
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: bash ./build.sh

    - name: Remove PDB files
      run: |
        find ./build -name "*.pdb" -type f -delete

    - uses: actions/upload-artifact@main
      with:
        name: "OTD.EnhancedOutputMode-0.6.x"
        path: |
          ./build/*
          !./build/*.pdb